name: Build Fedora

on:
  #  workflow_dispatch:
  push:
    
jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    
    steps:
      - uses: actions/checkout@v4
      - name: install_dependencies
        run: |
          cat /etc/os-release
          dnf -y upgrade
          dnf -y install libsdl2-dev
          dnf -y install libfreetype6-dev
          dnf -y install libfontconfig-dev
          dnf -y install libminiupnpc-dev
          dnf -y install libzstd-dev libglfw3-dev
          dnf -y install libglew-dev
          dnf -y install libopenal-dev

      - name: build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DOPTION_BUNDLE_LIBRARIES=ON -DSIMUTRANS_UPDATE_LANGFILES=ON
          cmake --build build -j$(nproc) --target install
  