name: Nightly Built Windows

on: [push]

jobs:
  mingw-opengl:
    runs-on: windows-latest
    steps:

      - name: Setup Mingw
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git zip unzip svn base-devel mingw-w64-x86_64-toolchain autoconf mingw-w64-x86_64-gcc mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-freetype mingw-w64-x86_64-zstd mingw-w64-x86_64-libpng mingw-w64-x86_64-brotli mingw-w64-x86_64-pkg-config mingw-w64-x86_64-glfw mingw-w64-x86_64-glew mingw-w64-x86_64-mesa mingw-w64-x86_64-openal
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepares NSIS plugins
        run: ./.github/prepare-nsis.ps1
        shell: powershell

      - name: Create nsis installer
        uses: joncloud/makensis-action@v4
        with:
          arguments: "/V3"
          additional-plugin-paths: NSIS_Plugins/Plugins
          script-file: src/Windows/nsis/onlineupgrade.nsi

      - name: CI-Build
        run: sh ./.github/build64-ogl.sh
        shell: msys2 {0}

      - name: Update binaries of Nightly Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./simuwin64-ogl-nightly.zip
          asset_name: simuwin_gl-x64.zip
          tag: Simutrans_GL_Nightly
          overwrite: true
