name: Update tag

on: [push]
    
jobs:
  update-nightly:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: detect revision
      run: |
        echo "revision=`tools/get_revision.sh`" >> $GITHUB_ENV

    - name: set current head to nightly
      uses: richardsimko/update-tag@v1
      with:
          tag_name: Simutrans_GL_Nightly
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: rename the release to include revision
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: Simutrans_GL_Nightly
        name: Simutrans GL nightly build r${{ env.revision }}
        body: Simutrans GL is a variant of Simutrans which uses Open GL to display the map. It can display graphics in 32 bpp and use transparency effects. It's work in progress.
        allow_override: true
